### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by m-qur**
Add CORS (If it ever malfunctions) and bypass SSL

### CODE REVIEW

**Comment by tristandevs** [comment]
oop

**Comment by tristandevs** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/shuttlenetwork/shuttle-lite/pull/2/conflicts) or the  to resolve conflicts.
Conflicting files
index.js

**Comment by m-qur** [comment]
uhm how do i fix thi sh

**Comment by tristandevs** [comment]
idk lmfao

**Pull request closed without merging**
